
/* errors code */
#ifndef BF_ERROR_CODES_H
#define BF_ERROR_CODES_H

typedef enum {
    BF_OK = 0,
    BF_ERR_MAX_SIZE_EXCEED,
    BF_ERR_MIN_SIZE_EXCEED,
    BF_ERR_MAX_BYTE_EXCEED,
    BF_ERR_MIN_BYTE_EXCEED,
    BF_ERR_ALLOCATION_FAILED,
    BF_ERR_INVALID_BYTE,

    BF_ERR_STKPTR_EXCEED_STK_SIZE,
    BF_ERR_STKPTR_BELOW_ZERO,

    BF_ERR_OPEN_FILE
} BF_error_codes;

#endif // BF_ERROR_CODES_H